apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: imgldr
    name: imgldr-controller-manager
    namespace: {{ .Release.Namespace }}
