# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
    permissions:
      contents: read

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
    permissions:
      contents: read

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    permissions:
      contents: read

  govulncheck:
    uses: ./.github/workflows/govulncheck.yml
    secrets: inherit
    permissions:
      contents: read

  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write

  e2e-tests:
    needs:
      - "build"
      - "lint"
      - "pre-commit"
      - "unit-tests"
      - "govulncheck"
      - "codeql"
    strategy:
      fail-fast: false
    name: e2e-tests
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    permissions:
      contents: read
      checks: write
