# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: conventional-label

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-24.04
    steps:
      - uses: bcoe/conventional-release-labels@v1
